resources:

- repo: self

queue:

  name: Hosted macOS Preview

  demands: 

  - xcode

  - Xamarin.iOS





#Your build definition references an undefined variable named ‘build.artifactstagingdirectory’. Create or edit the build definition for this YAML file, define the variable on the Variables tab. See https://go.microsoft.com/fwlink/?linkid=865972

#Your build definition references an undefined variable named ‘build.artifactstagingdirectory’. Create or edit the build definition for this YAML file, define the variable on the Variables tab. See https://go.microsoft.com/fwlink/?linkid=865972

variables:

  BuildConfiguration: 'debug'

steps:

- task: InstallAppleCertificate@1

  inputs:

    certSecureFile: '7df9519d-61ce-4241-b9d4-cfe0db691f62'

    certPwd: test123



- task: InstallAppleProvisioningProfile@1

  inputs:

    provProfileSecureFile: '2ee0e2e1-77f5-4cf4-883c-7e56fff6e168'



- task: colinsalmcorner.colinsalmcorner-buildtasks.replace-tokens-task.ReplaceTokens@1

  enabled: false



- task: NuGetCommand@2



- task: XamariniOS@1

  inputs:

    solutionFile: 'HealthClinic/HealthClinic.sln'

    configuration: '$(BuildConfiguration)'

    clean: true

    buildToolOption: msbuild



- task: AppCenterTest@1

  inputs:

    appFile: 'HealthClinic/HealthClinic.iOS/bin/iPhone/Debug/HealthClinic.iOS.ipa'

    frameworkOption: uitest

    uiTestBuildDirectory: 'HealthClinic/HealthClinic.UITests/bin/Debug'

    serverEndpoint: AppCenter

    appSlug: 'xandersparks/MercuryHealthiOS'

    devices: 'xandersparks/mercuryhealthmobileset'

    skipWaitingForResults: true



- task: CopyFiles@2

  inputs:

    Contents: |
     **/*.ipa
     **/HealthClinic.UITests/**/*.dll
     src/ReleaseNotes.txt
     **/test-cloud.exe

    TargetFolder: '$(build.artifactstagingdirectory)'



- task: PublishBuildArtifacts@1

  inputs:

    PathtoPublish: '$(build.artifactstagingdirectory)'

    ArtifactName: mobile

    publishLocation: Container




