apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: techreadydemo-prod
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  minReadySeconds: 5
  template: # create pods using pod definition in this template
    metadata:
      labels:
        app: techreadydemo-prod
    spec:
      containers:
      - name: techreadydemo-prod
        image: abelcontainerregistry.azurecr.io/techreadydemo:latest
        env:
        - name: Local
          value: "false"
        - name: ASPNETCORE_URLS
          value: "http://+:80"        
        ports:
        - containerPort: 80
      imagePullSecrets:
        - name: azurecontainerreg
---
apiVersion: v1
kind: Service
metadata:
  name: techreadydemo-prod
spec:
  type: ClusterIP
  ports:
  - port: 80
  selector:
    app: techreadydemo-prod
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: techreadydemo-prod-ingress
  annotations:
    kubernetes.io/ingress.class: "nginx"
    kubernetes.io/tls-acme: "true"
spec:
  rules:
    - host: prod.tr.aks.az.jessicadeen.com
      http:
        paths:
          - backend:
              serviceName: techreadydemo-prod
              servicePort: 80
  tls:
    - secretName: prod.tr.aks.az.jessicadeen.com
      hosts:
      - prod.tr.aks.az.jessicadeen.com