version: '3'

services:
  ci-build:
    image: microsoft/aspnetcore-build:1.0-2.0
    volumes:
      - .:/
    working_dir: /
    command: /bin/bash -c "dotnet restore ./MercuryHealthServices.sln && dotnet publish ./MercuryHealthServices.sln -c Release -o ./obj/Docker/publish"
